In [1]:
#referencia https://medium.com/towards-artificial-intelligence/multi-class-text-classification-using-pyspark-mllib-doc2vec-dbfcee5b39f2
import findspark
findspark.init() 
from pyspark.sql import SparkSession
import os


MAX_MEMORY = "8g"
spark = SparkSession.builder \
                    .master("local") \
                    .appName('va_repositorio')\
                    .config("spark.executor.memory", MAX_MEMORY) \
                    .config("spark.driver.memory", MAX_MEMORY) \
                    .config("spark.jars", "E:\\va\\driverdb\\postgresql-42.2.5.jre6") \
                    .getOrCreate()

In [2]:
tabla="proyecto.view_clase_va"
df  = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:postgresql://localhost:5432/va") \
    .option("dbtable", tabla) \
    .option("user", "postgres") \
    .option("password", "david") \
    .option("driver", "org.postgresql.Driver") \
    .load()
df.printSchema()

root
 |-- periodo: string (nullable = true)
 |-- estu_mcpio_reside: string (nullable = true)
 |-- estu_genero: string (nullable = true)
 |-- estu_estadocivil: string (nullable = true)
 |-- estu_etnia: string (nullable = true)
 |-- estu_limita_motriz: string (nullable = true)
 |-- estu_limita_invidente: string (nullable = true)
 |-- estu_limita_sordoconinterprete: string (nullable = true)
 |-- estu_limita_sordosininterprete: string (nullable = true)
 |-- estu_limita_sordoceguera: string (nullable = true)
 |-- estu_porcentajecreditosaprob: string (nullable = true)
 |-- estu_valormatriculauniversidad: string (nullable = true)
 |-- estu_pagomatriculabeca: string (nullable = true)
 |-- estu_pagomatriculacredito: string (nullable = true)
 |-- estu_pagomatriculapadres: string (nullable = true)
 |-- estu_pagomatriculapropio: string (nullable = true)
 |-- estu_tomo_cursopreparacion: string (nullable = true)
 |-- estu_cursodocentesies: string (nullable = true)
 |-- estu_cursoiesapoyoexterno: string (nullable = true)
 |-- estu_cursoiesexterna: string (nullable = true)
 |-- estu_simulacrotipoicfes: string (nullable = true)
 |-- estu_actividadrefuerzoareas: string (nullable = true)
 |-- estu_actividadrefuerzogeneric: string (nullable = true)
 |-- estu_semestrecursa: string (nullable = true)
 |-- fami_hogaractual: string (nullable = true)
 |-- fami_cabezafamilia: string (nullable = true)
 |-- fami_numpersonasacargo: string (nullable = true)
 |-- fami_educacionpadre: string (nullable = true)
 |-- fami_educacionmadre: string (nullable = true)
 |-- fami_ocupacionpadre: string (nullable = true)
 |-- fami_ocupacionmadre: string (nullable = true)
 |-- fami_estratovivienda: string (nullable = true)
 |-- fami_nivel_sisben: string (nullable = true)
 |-- fami_personashogar: string (nullable = true)
 |-- fami_cuartoshogar: string (nullable = true)
 |-- fami_pisos_hogar: string (nullable = true)
 |-- fami_tieneinternet: string (nullable = true)
 |-- fami_tiene_serviciotv: string (nullable = true)
 |-- fami_tienecomputador: string (nullable = true)
 |-- fami_tienelavadora: string (nullable = true)
 |-- fami_tiene_microondas: string (nullable = true)
 |-- fami_tiene_horno: string (nullable = true)
 |-- fami_tieneautomovil: string (nullable = true)
 |-- fami_tiene_dvd: string (nullable = true)
 |-- fami_tiene_nevera: string (nullable = true)
 |-- fami_tiene_celular: string (nullable = true)
 |-- fami_telefono: string (nullable = true)
 |-- fami_tienehornomicroogas: string (nullable = true)
 |-- fami_tienemotocicleta: string (nullable = true)
 |-- fami_numlibros: string (nullable = true)
 |-- estu_dedicacionlecturadiaria: string (nullable = true)
 |-- estu_dedicacioninternet: string (nullable = true)
 |-- fami_tieneconsolavideojuegos: string (nullable = true)
 |-- fami_cuantoscompartebano: string (nullable = true)
 |-- fami_ingreso_fmiliar_mensual: string (nullable = true)
 |-- estu_trabaja_actualmente: string (nullable = true)
 |-- estu_horassemanatrabaja: string (nullable = true)
 |-- estu_tiporemuneracion: string (nullable = true)
 |-- estu_prgm_academico: string (nullable = true)
 |-- gruporeferencia: string (nullable = true)
 |-- inst_origen: string (nullable = true)
 |-- estu_privado_libertad: string (nullable = true)
 |-- estu_nse_individual: string (nullable = true)
 |-- estu_nse_ies: string (nullable = true)
 |-- estu_consecutivo: string (nullable = true)
 |-- clase_va_razonamiento_cuantitativo: integer (nullable = true)
 |-- clase_va_lectura_critica: integer (nullable = true)
 |-- clase_va_competencias_ciudadanas: integer (nullable = true)
 |-- clase_va_ingles: integer (nullable = true)

In [27]:
#CONVERTIR EL DF A TO PANDAS
df_pan=df.toPandas()

In [28]:
df_pan.head()

,periodo,estu_mcpio_reside,estu_genero,estu_estadocivil,estu_etnia,estu_limita_motriz,estu_limita_invidente,estu_limita_sordoconinterprete,estu_limita_sordosininterprete,estu_limita_sordoceguera,...,gruporeferencia,inst_origen,estu_privado_libertad,estu_nse_individual,estu_nse_ies,estu_consecutivo,clase_va_razonamiento_cuantitativo,clase_va_lectura_critica,clase_va_competencias_ciudadanas,clase_va_ingles
0,20133,pasto,f,soltero,,,,,,,...,ingenieria,oficial_departamental,n,no_aplica,no_aplica,ek201330163566,1,0,1,1
1,20143,pasto,m,soltero,,,,,,,...,ingenieria,oficial_departamental,n,no_aplica,no_aplica,ek201430224000,0,1,1,1
2,20183,ipiales,m,soltero,comunidad_afrodescendiente,no_aplica,no_aplica,no_aplica,no_aplica,no_aplica,...,ingenieria,oficial_departamental,n,,1,ek201830012727,0,0,0,0
3,20123,pasto,f,soltero,no_aplica,no_aplica,no_aplica,no_aplica,no_aplica,no_aplica,...,educacion,oficial_departamental,n,no_aplica,no_aplica,ek201230111186,1,1,0,0
4,20133,pasto,m,soltero,,,,,,,...,economia,oficial_departamental,n,no_aplica,no_aplica,ek201330164239,1,0,1,1

In [33]:
#CONVERTIR VARIABLES A DUMMIES 
import pandas as pd
df_va_dummies= pd.get_dummies(df_pan)

In [36]:
df_va_dummies.head(100)

,clase_va_razonamiento_cuantitativo,clase_va_lectura_critica,clase_va_competencias_ciudadanas,clase_va_ingles,periodo_20121,periodo_20123,periodo_20131,periodo_20133,periodo_20142,periodo_20143,...,estu_consecutivo_ek201830230286,estu_consecutivo_ek201830238901,estu_consecutivo_ek201830240557,estu_consecutivo_ek201830240706,estu_consecutivo_ek201830240823,estu_consecutivo_ek201830240999,estu_consecutivo_ek201830241690,estu_consecutivo_ek201830242112,estu_consecutivo_ek201830242550,estu_consecutivo_ek201830242637
0,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,1,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,1,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,1,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
99,1,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0